AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  Okido:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./line
      Handler: server.handler
      Runtime: nodejs14.x
      Timeout: 180
      Events:
        hooks:
          Type: Api
          Properties:
            Path: /hooks
            Method: POST
      Environment:
        Variables:
          OPENAI_API_TOKEN: Dummy
          EXEC_LOCAL: "false"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - src/server.ts
          